### ISSUE TITLE
Drop Support for PHP 5.5

### ISSUE THREAD

**Issue by svpernova09** [phergie/phergie-irc-plugin-react-bofh#2]

**Comment by elstamey** [comment]
as a note, this hits the guzzle warning because it has `require-dev` with `"phergie/phergie-irc-bot-react-development": "~1.0"`

the `extra` seems to keep it fixed on `1.0` release.  Is that correct?

**Comment by svpernova09** [comment]
The `extra` shouldn't have any impact on this repo as we're not using `dev-master` anywhere.

I wouldn't worry about the guzzle warning so long as we're sure it's coming from a package that isn't ours.

**Comment by elstamey** [comment]
Thanks, just wanted to be sure additional cleanup wasn't needed.
